services:
  mysql:
    image: mysql:8.0
    container_name: licenta_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: licenta_db
      MYSQL_USER: licenta_user
      MYSQL_PASSWORD: licenta_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: