"""unique task dependency

Revision ID: 2737c5dec706
Revises: 58723ac6adc9
Create Date: 2026-03-16 11:40:26.034775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2737c5dec706'
down_revision: Union[str, Sequence[str], None] = '58723ac6adc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_dependency', 'task_dependencies', ['project_id', 'predecessor_task_id', 'successor_task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_dependency', 'task_dependencies', type_='unique')
    # ### end Alembic commands ###
