"""unique project title per owner

Revision ID: a016de2561ca
Revises: e9572197330e
Create Date: 2026-03-18 21:53:26.110054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a016de2561ca'
down_revision: Union[str, Sequence[str], None] = 'e9572197330e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_owner_title', 'projects', ['created_by', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_owner_title', 'projects', type_='unique')
    # ### end Alembic commands ###
