"""unique user_skill

Revision ID: ae06a50dd795
Revises: 2737c5dec706
Create Date: 2026-03-16 18:41:12.184725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae06a50dd795'
down_revision: Union[str, Sequence[str], None] = '2737c5dec706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    # ### end Alembic commands ###
