"""unique task assignments

Revision ID: b003878df9a0
Revises: ae06a50dd795
Create Date: 2026-03-16 20:05:52.819704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b003878df9a0'
down_revision: Union[str, Sequence[str], None] = 'ae06a50dd795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_assignment', 'task_assignments', ['task_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_assignment', 'task_assignments', type_='unique')
    # ### end Alembic commands ###
