"""unique task skill requirements

Revision ID: e9572197330e
Revises: b003878df9a0
Create Date: 2026-03-16 20:06:41.795036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9572197330e'
down_revision: Union[str, Sequence[str], None] = 'b003878df9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_skill_req', 'task_skill_requirements', ['task_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_skill_req', 'task_skill_requirements', type_='unique')
    # ### end Alembic commands ###
